### ISSUE TITLE
Automatic submission of configuration files

### ISSUE THREAD

**Issue by silkenelson** [pcdshub/IocManager#2]
Move the commit process from the application to an automated process to be run regularly (every 24h?) and remove related code from GUI. 

This will make sure that configuration can be recovered even when people did not feel they were ready. It also allows the "commit host" aka 'host that holds the file lock'  to be a machine more accessible e.g. to beamline staff.

**Comment by klauer** [comment]
I think this is outdated with the new `git`-based committing mechanism. OK to close?

**Comment by silkenelson** [comment]
I believe so.
