### ISSUE TITLE
IOCs failing to boot

### ISSUE THREAD

**Issue by klauer** [pcdshub/IocManager#4]
Symptom
-----------
```
@@@ @@@ @@@ @@@ @@@
@@@ Received a sigChild for process 15300. The process was killed by signal 9
@@@ Current time: Wed Jun  9 16:15:00 2021
@@@ Child process is shutting down, a new one will be restarted shortly
@@@ ^R or ^X restarts the child, ^Q quits the server
@@@ Restarting child "ioc-mfx-tfs-lens"
@@@    (as /reg/g/pcds/pyps/config/mfx/iocmanager/startProc)
@@@ The PID of new child "ioc-mfx-tfs-lens" is: 15734
@@@ @@@ @@@ @@@ @@@
```

and nothing happens, even waiting a long time. No output except for what procServ dumps out.

I've seen this happen multiple times, and things usually recover at some point (30 mins or more?).

Guess
--------

I think some of the config-related tools can create problems. My guess is that the lock acquisition and our poor, finicky network filesystems create hostile environments for these tools:

```
$ python /reg/g/pcds/pyps/config/mfx/iocmanager/getDirectory.py ioc-mfx-tfs-lens mfx
```
The above locks the terminal, blocking Ctrl-C and even Ctrl-Z for the longest time. 3 minutes later, and still no luck getting the IOC directory.

strace
--------

Let's see what `strace` shows...
Oh, now it's back to working, so `strace` output is useless.

Suspicious code?
-----------------

I'd guess it hangs here: https://github.com/pcdshub/IocManager/blob/39a284dbf41d84f743d78e994654f160c1337383/utils.py#L490

Any thoughts on the above or where else it might be, @mcb64?

**Comment by mcb64** [comment]
I think this is a very accurate assessment.  However, I'm not sure what to do here.  If we don't lock, it's unlikely we'd be starting at the same time as a file update, but...

The basic problem is that Linux file locking in an NFS environment is notoriously unreliable.  And we're not using a real DB here... just a text file.

That said... perhaps the solution is to switch to mongoDB or something similar and let it take care of the concurrent operations?  (We're basically just reading the text file into a dictionary.  No reason we couldn't do something similar in a mongoDB.  Even if we just dumped the entire hutch configuration into one document/record/whatever the hell they are called.

**Comment by mcb64** [comment]
Yeah, it's probably safe enough to just remove it.

This whole 'commithost' thing is for the birds though.  It would be good to just use a db somewhere and let it deal with everything.

**Comment by mcb64** [comment]
Incidently, this doesn't seem to be the problem.  I was running into this on ioc-xpp-rec03, and so I commented out the locking.  Nope.

**Comment by klauer** [comment]
Huh, darn ☹️ Did `getDirectory` when called manually fail to run for that machine? `strace` on that perhaps?

(It has to be network file system *something* I feel, but I've been wrong many-a-time before...)

**Comment by mcb64** [comment]
Yeah, it seems to be failing in general.  I agree, it's a file system problem... maybe the exclusive locking is screwing things up worse than I thought?
    --Mike

________________________________

**Comment by klauer** [comment]
This was due to file system issues. Closing as "cannot reproduce"
